# Generated by Django 4.2.1 on 2023-05-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("building", models.PositiveSmallIntegerField()),
                ("floor", models.PositiveSmallIntegerField()),
                ("PCsNumber", models.PositiveSmallIntegerField()),
                ("ChairsNumber", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Under Maintenance", "Under Maintenance"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pcId", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Under Maintenance", "Under Maintenance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LabApp.lab"
                    ),
                ),
            ],
            options={
                "unique_together": {("pcId", "lab")},
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reportId", models.PositiveSmallIntegerField(unique=True)),
                ("data", models.DateField(auto_now=True)),
                (
                    "problemType",
                    models.CharField(
                        choices=[("Software", "Software"), ("Hardware", "Hardware")],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LabApp.lab"
                    ),
                ),
                (
                    "pcNumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LabApp.pc"
                    ),
                ),
            ],
        ),
    ]
