# Generated by Django 4.2.1 on 2023-05-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LabApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("reportId", "lab")},
        ),
    ]
