# Generated by Django 4.1.5 on 2023-05-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LabApp", "0002_alter_report_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="data",
            new_name="date",
        ),
    ]
