# Generated by Django 4.1.5 on 2023-05-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LabApp", "0003_rename_data_report_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="report",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="report",
            name="reportId",
        ),
    ]
